In [3]:
# Introduction to Tensors

In [4]:
%pip install -q sklearn

In [5]:
%tensorflow_version 2.x

Colab only includes TensorFlow 2.x; %tensorflow_version has no effect.


In [73]:
# Import tensorflow
import tensorflow as tf
print(tf.__version__)

2.8.2


## Creating tensors with `tf.constant`


In [7]:
scalar = tf.constant(5)
print(scalar)

tf.Tensor(5, shape=(), dtype=int32)


In [8]:
# Check the number of dimensions of a tensor (ndim stands for number of dimensions)
scalar.ndim

0

In [9]:
# Creating a vector
vector = tf.constant([10, 10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [10]:
# Checking the domension of the vector
vector.ndim

1

In [11]:
# Create a matrix
matrix = tf.constant([[], []])
matrix

<tf.Tensor: shape=(2, 0), dtype=float32, numpy=array([], shape=(2, 0), dtype=float32)>

In [12]:
# Checkig the dimensions of the matrix
matrix.ndim

2

In [13]:
another_matrix = tf.constant([[10., 7.], [3., 2.], [8., 5.]], dtype=tf.float16)
another_matrix

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[10.,  7.],
       [ 3.,  2.],
       [ 8.,  5.]], dtype=float16)>

## Creating tensors with ```tf.Variable```

In [14]:
tf.Variable

tensorflow.python.ops.variables.Variable

In [15]:
changeble_vector = tf.Variable([[10, 3], [23, 21], [3, 88]])
changeble_vector[0, 1].assign(6)

<tf.Variable 'UnreadVariable' shape=(3, 2) dtype=int32, numpy=
array([[10,  6],
       [23, 21],
       [ 3, 88]], dtype=int32)>

## Creating random tensors

Random tensors are tensors of some arbitrary size which contain random numbers

In [16]:
# Creating random tensors
random_1 = tf.random.Generator.from_seed(10) # set seed for reproducibility
random_1 = random_1.normal(shape=(3, 2))
random_2 = tf.random.Generator.from_seed(10)
random_2 = random_2.normal(shape=(3, 2))

# Are they equal??
print(random_1 == random_2)


tf.Tensor(
[[ True  True]
 [ True  True]
 [ True  True]], shape=(3, 2), dtype=bool)


## Shuffle the order of a Tensor

In [17]:
# shuffle a tensor
ns = tf.constant([[10, 5], [3, 6], [2, 56]])
tf.random.set_seed(10) # global level random seed
tf.random.shuffle(ns)


<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  5],
       [ 2, 56],
       [ 3,  6]], dtype=int32)>

⚔ **Exercise :** Read through the Tensorflow Documentation on random seed generation: https://www.tensorflow.org/api_docs/python/tf/random/set_seed and practice writing 5 random tensors and shuffle them. 

## Other ways of making a tensor

In [18]:
# tf.ones([3, 4], tf.float16)
import numpy as np
numpy_a = [np.arange(1, 25, dtype=np.int32)]
numpy_a

A = tf.constant(numpy_a, shape=(2, 2, 6), dtype=tf.int16, name="const")
A

<tf.Tensor: shape=(2, 2, 6), dtype=int16, numpy=
array([[[ 1,  2,  3,  4,  5,  6],
        [ 7,  8,  9, 10, 11, 12]],

       [[13, 14, 15, 16, 17, 18],
        [19, 20, 21, 22, 23, 24]]], dtype=int16)>

## Getting information from tensors

In [19]:
# Creating a rank 4 tensor
rank_4 = tf.zeros(shape=[2, 3, 4, 5])
rank_4.shape, rank_4.ndim, tf.size(rank_4)

(TensorShape([2, 3, 4, 5]), 4, <tf.Tensor: shape=(), dtype=int32, numpy=120>)

In [20]:
# Get various attributes of our tensor
print(f"Datatypes of every elements: {rank_4.dtype}")
print(f"Number of dimensions (rank): {rank_4.ndim}")
print(f"Shape of a tensor: {rank_4.shape}")
print(f"Elements along the 0 axis: {rank_4.shape[0]}")
print(f"Elements along the last axis: {rank_4.shape[-1]}")
print(f"Total number of elements in our tensor: {tf.size(rank_4)}")

Datatypes of every elements: <dtype: 'float32'>
Number of dimensions (rank): 4
Shape of a tensor: (2, 3, 4, 5)
Elements along the 0 axis: 2
Elements along the last axis: 5
Total number of elements in our tensor: 120


## Indexing tensors
Tensors can be indexed just like Python Lists

In [21]:
# Get the first 2 elements of each dimension
rank_4[:2, :2, :2, :2]

<tf.Tensor: shape=(2, 2, 2, 2), dtype=float32, numpy=
array([[[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]]], dtype=float32)>

In [22]:
rank_2_tensor = [[10, 7], [3, 4]]
rank_2_tensor

# Add in extra dimension to our rank 2 tensor
rank_3 = tf.expand_dims(rank_2_tensor, axis=0)
tf.shape(rank_3)
rank_3


<tf.Tensor: shape=(1, 2, 2), dtype=int32, numpy=
array([[[10,  7],
        [ 3,  4]]], dtype=int32)>

## Manipulating tensors (tensor operations)

In [23]:
# adding values to a tensor using the addition operator
tensor = tf.constant([[10, 7], [3, 4]])
tensor + 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 17],
       [13, 14]], dtype=int32)>

In [24]:
add = tensor[0] - tensor[1]
add

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([7, 3], dtype=int32)>

In [25]:
# Using the tensorflow built-in function
tf.multiply(tensor[0], tensor[1])

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([30, 28], dtype=int32)>

**Matrix Multiplication**

In machine learning matrix multiplication is one of the most commonly used tensor operations

There are two rules our tensors (or matrices) need to fulfill if we're going to matrix multiply them:

1. The inner dimensions must match
2. The resulting matrix has the shape of the outer dimensions

In [26]:
# matrix multiplication in tensorflow
tensor
tf.matmul(tensor, tensor)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[121,  98],
       [ 42,  37]], dtype=int32)>

In [27]:
t1 = tf.constant([[1, 2], [0, 1], [2, 3]])
t2 = tf.constant([[2, 5], [6, 7], [1, 8]])
t3 = tf.transpose(t2)
t3

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[2, 6, 1],
       [5, 7, 8]], dtype=int32)>

In [28]:
t1 = tf.constant([[1, 2], [0, 1], [2, 3]])
t2 = tf.constant([[2, 5], [6, 7], [1, 8]])
t3 = tf.reshape(t2, [2, 3])
t3

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[2, 5, 6],
       [7, 1, 8]], dtype=int32)>

Generally, when performing matrix multiplication on two tensors and one of the axes dosen't line up, you will transpose rather than reshape one of the tensors to satisfy the matrix multiplication rules.

## Changing the dtype of a tensor

In [29]:
# Create a new tensor with default datatype (float32)
b = tf.constant([1.3, 4.6])
b.dtype

# Change from float32 to float16(reduced precision)
b = tf.cast(b, dtype=tf.float16)
b

<tf.Tensor: shape=(2,), dtype=float16, numpy=array([1.3, 4.6], dtype=float16)>

In [ ]:
e = tf.constant([1, 4, 6])
f = tf.cast(e, dtype=tf.float16)
f

## Aggregating tensors

Aggregating tensors = condensing them from multiple values down to a smaller amount of values

In [ ]:
# Get the absolute values
d = tf.constant([-7, -10])
tf.abs(d)

### Operation on aggregation
1. Get the minimum
2. Get the maximum
3. Get the sum of a tensor
4. Get the mean of a tensor

In [ ]:
# Creating a random tensor with values between 0 and 100 of size 50
e = tf.constant(tf.random.uniform([50], 0, 100, tf.dtypes.float16))
e

In [ ]:
# Find the minimum
m = tf.reduce_min(e)

# Find the maximum
M = tf.reduce_max(e)

# Find the mean
mean = tf.reduce_mean(e)

# Find the sum
s = tf.reduce_sum(e)

print(m, M, mean, s)

🛠 **Exercise:** Find the variance and the standard daviation of the tensor `e`

In [ ]:
# Find the varinace
variance = tf.math.reduce_variance(e)

# Find the standard deviation
std_dev = tf.math.reduce_std(e)

print(variance, std_dev)

## Find the positional maximum and minimum


In [ ]:
# Create a new tensor forfinding positional minimum and maximum
tf.random.set_seed(42)
f = tf.random.uniform([17, 3], dtype=tf.dtypes.float16)
f

In [ ]:
i = tf.math.argmax(f)
i_m = tf.math.argmin(f)
m = tf.reduce_max(f)

print(i, m, i_m)

## Squeezing a tensor (removing all single dimensions)

In [ ]:
# Create a tensor to get started
tf.random.set_seed(42)
g = tf.constant(tf.random.uniform([50]), shape=(1, 1, 1, 1, 50))
g

In [ ]:
g_squeezed = tf.squeeze(g)
g_squeezed

## One-Hot encoding tensors

In [ ]:
# Create a list of indices
some_list = [0, 1, 2, 3]

# one hot encode
tf.one_hot(some_list, 4, on_value=5, off_value=0)

## Squaring, log, Square Root

In [ ]:
tf.math.log(tf.cast(some_list, dtype=tf.float16))

## Tensors and Numpy

Tensorflow interacts beautifully with numpy ARRAYS

In [ ]:
# create a tensor directly from a numpy array
j = tf.constant(np.array([3, 7, 10]))
j

In [ ]:
# Convert out a tensor to a numpy array
np.array(j), type(np.array(j))